; PlatformIO — Robot Diferencial · Firmware ESP32 (ESP-IDF, C nativo)
; Abrí ESTA carpeta (esp32_diff/) en VS Code con PlatformIO. Build → Upload → Monitor.

[platformio]
src_dir = main

[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = espidf
monitor_speed = 115200
upload_speed  = 921600
